services:
  web_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:web_app --host 0.0.0.0 --port 7000 --reload
    depends_on:
      - db
    environment:
      DB_URL: postgresql+asyncpg://postgres:password@db:5432/mydatabase
    ports:
      - "8000:7000"
    volumes:
      - ./app:/src
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
