services:
  web_app:
    build:
      context: .
    container_name: fastapi_app
    command: uvicorn main:web_app --host 0.0.0.0 --port 7000 --reload
    depends_on:
      - db
    ports:
      - "8000:7000"
    volumes:
      - ./app:/src
  db:
    image: postgres
    container_name: postgres_db
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
